name = input("Enter Name: ")
usn = input("Enter USN: ")
branch = input("Enter Branch: ")
college = input("Enter College: ")
age = int(input("Enter Age: "))

print("\n----- Student Profile -----")
print(f"Name: {name}")
print(f"USN: {usn}")
print(f"Branch: {branch}")
print(f"College: {college}")
print(f"Age: {age}")

print("\n----- Name Analysis -----")
print("Upper:", name.upper())
print("Lower:", name.lower())
print("Length:", len(name))
print("First Letter:", name[0])
print("Last Letter:", name[-1])
print("Branch Lowercase:", branch.lower())
