name=input('enter student name>>')
USN=input("enter USN of student>>")
branch=input("branch name>>")
print(name[6])
print(f"I am {name}.My USN is{USN}.And branch is{branch}")
print(type(branch))
